### ISSUE TITLE
Error code ELIFECYCLE

### ISSUE THREAD

**Issue by hieyou1** [fossage/ASCII-Video#5]
Here is the code log:
[debug.log](https://github.com/fossage/ASCII-Video/files/2195943/debug.log)
I have honestly no idea what I did wrong.
GraphicsMagick is installed.
I am on Ubuntu Linux 16.04 LTS.
plshelpthxbye

**Comment by hieyou1** [comment]
@fossage can you help pls

**Comment by hieyou1** [comment]
@fossage @xinyichen @jzarca01 please?

**Comment by jzarca01** [comment]
See https://github.com/azachar/protractor-screenshoter-plugin/issues/45

**Comment by fossage** [comment]
@hieyou1 , hey sorry for the late reply.  The notification got buried in my inbox.  Have you resolved the issue?  If so, can you share your solution, and if not can you tell me which version of node you are using?

**Comment by hieyou1** [comment]
No.
Node v10.0.0
NPM v6.2.0
